### ISSUE TITLE
ArtifactNotFoundException: Could not find paging-0.4.5-samplessources.jar

### ISSUE THREAD

**Issue by Drjacky** [icerockdev/moko-paging#36]
```groovy
Failed building KotlinMPPGradleModel
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find paging-0.4.5-samplessources.jar (dev.icerock.moko:paging:0.4.5).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/dev/icerock/moko/paging/0.4.5/paging-0.4.5-samplessources.jar
```

My usage:
shared module:
```kotlin
sourceSets {
        val commonMain by getting {
            dependencies {
                ...
                api("dev.icerock.moko:paging:$mokoPagingVersion")
            }
        }
```

**Comment by Alex009** [comment]
hi! i think you have targets that not supported by paging lib. for example jvm. 
library support only android & ios targets.
this comment can help you in this case - https://github.com/icerockdev/moko-resources/issues/133#issuecomment-740700058

**Comment by Drjacky** [comment]
```kotlin
sourceSets {
        val commonMain by getting {
            dependencies {
                ...
                api("dev.icerock.moko:paging:$mokoPagingVersion")
            }
        }

        val mobileMain by creating {
            dependsOn(commonMain)
        }

        val jvmMain by getting {
            dependencies {
                //actually empty
            }
        }

        val androidMain by getting {
            dependsOn(mobileMain)
            dependsOn(jvmMain)
            dependencies {
               ...
            }
        }

        val iosMain by getting {
            dependsOn(mobileMain)
            dependencies {
                ...
            }
        }

        all {
            languageSettings.useExperimentalAnnotation("kotlin.RequiresOptIn")
        }
    }
```

**Comment by Drjacky** [comment]
@Alex009 That issue solved.
I know this one is not related to the library itself but, it doesn't matter where I add the dependency(shared, android), the package cannot be recognized!

Adding here
<img width="579" alt="Screen Shot 2021-05-23 at 12 32 12" src="https://user-images.githubusercontent.com/2296754/119258736-e847c800-bbc2-11eb-97d0-ca782aea1b7d.png">
Or here
<img width="606" alt="Screen Shot 2021-05-23 at 12 32 33" src="https://user-images.githubusercontent.com/2296754/119258747-f4cc2080-bbc2-11eb-90bd-989cb245b5e4.png">
Or here
<img width="617" alt="Screen Shot 2021-05-23 at 12 32 49" src="https://user-images.githubusercontent.com/2296754/119258756-fdbcf200-bbc2-11eb-8142-cc28b2958788.png">

It doesn't matter, the result is same:
<img width="359" alt="Screen Shot 2021-05-23 at 12 31 59" src="https://user-images.githubusercontent.com/2296754/119258725-e0882380-bbc2-11eb-95b7-55622c6e6383.png">
