### ISSUE TITLE
Publish for JVM

### ISSUE THREAD

**Issue by msfjarvis** [icerockdev/moko-paging#55]
Looking at the code I don't see anything specific that would make this any more complex than just adding a JVM target. With [compose-jb](https://github.com/jetbrains/compose-jb) allowing code sharing between mobile and desktop for UI, being able to share UI logic like pagination using this library would be immensely helpful.

**Comment by msfjarvis** [comment]
Would there be interest in a PR for this? I require the functionality for a personal project and am willing to resolve this.

**Comment by Alex009** [comment]
@msfjarvis yes, it will be great

**Comment by Alex009** [comment]
will be available in 0.7.0

**Comment by msfjarvis** [comment]
Thank you!
